function testrk2(N,y_0,f,T)
% TESTRK2 the function which can be used to calculate the error of the 
% solution generated by applying 2-step Runge-Kutta method
% Input
%      N    number of iterations
%      y_0  intial value
%      f    the RHS funciton
%      T    final time
load datark2.mat
tspan = [0:T/N:T];
[time,y_true] = ode45(f,tspan,y_0);
error = abs(y_true-y);
two_norm_of_error = norm(error)
inf_norm_of_error = norm(error,Inf)
error_rela = error./abs(y_true);
two_norm_of_error_rela = norm(error_rela)
inf_norm_of_error_rela = norm(error_rela,Inf)
plot(tspan,y,'bo',tspan,y_true,'r*',tspan,error,'g*',tspan,error_rela, 'yo')
legend('2-step Runge-kutta Method','True solution','Error')